database:
  uri: "mongodb://localhost:27017/studie_link"

secret_key: secret

client_secret_file_location: client_secrets.json

eduid:
  register_url: http://eduid.localhost:8080/api/v1/register
  provision_client_url: http://eduid.localhost:8080/api/v1/provision-client
  user: admin
  password: secret
  client_id: studie_link
